

services: 
  db:
    image: postgres
    restart: always
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /var/lib/postgresql/data
    env_file: 
      - .env
    container_name: postgres_db

  adminer:
    image: adminer
    restart: always
    ports: 
      - ${ADMINER_PORT}:${ADMINER_PORT}
    env_file: 
      - .env

  migration:
    image: postgres 
    depends_on:
      - db
    volumes:
      - ./pkg/db/schema/:/pkg/db/schema/
    command: ["psql", "-h", "db", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-a", "-f", "/pkg/db/schema/init.up.sql"]
    environment: 
      - PGPASSWORD=${DB_PASSWORD}
    restart: on-failure
    env_file: 
      - .env
    container_name: migration